
let midiFile=null,arrayBuffer=null,header=null,allEvents=[],tokens=[],ticksPerBeat=480,timeDivisionEnum=null;
const $=s=>document.querySelector(s),showMsg=s=>document.getElementById('msg').textContent=s;

document.getElementById('btnLoad').addEventListener('click',async()=>{
  const f=document.getElementById('fileInput').files[0];
  if(!f) return showMsg('Choose a MIDI/KAR file first.');
  arrayBuffer=await f.arrayBuffer();
  try{
    midiFile=new MIDIFile(arrayBuffer);
    header={format:midiFile.header.getFormat(),tracksCount:midiFile.header.getTracksCount(),timeDivision:midiFile.header.getTimeDivision()};
    if(header.timeDivision===MIDIFile.Header.TICKS_PER_BEAT){ticksPerBeat=midiFile.header.getTicksPerBeat();timeDivisionEnum=MIDIFile.Header.TICKS_PER_BEAT;}else{timeDivisionEnum=header.timeDivision;}
    allEvents=[];
    for(let t=0;t<header.tracksCount;t++){const evs=midiFile.getTrackEvents(t);evs.forEach((ev,idx)=>{allEvents.push({track:t,idx,type:ev.type,metaType:ev.metaType,delta:ev.delta,playTime:ev.playTime??0,text:ev.text||''});});}
    renderEvents();showMsg(`Parsed OK. Tracks=${header.tracksCount}, division=${header.timeDivision}.`);
  }catch(e){console.error(e);showMsg('Failed to parse with MIDIFile.js.');}
});

document.getElementById('onlyLyrics').addEventListener('change',renderEvents);
document.getElementById('interpret').addEventListener('change',renderEvents);

function renderEvents(){const onlyLy=document.getElementById('onlyLyrics').checked;const interpret=document.getElementById('interpret').checked;const tbody=document.querySelector('#eventsTbl tbody');tbody.innerHTML='';const rows=allEvents.filter(ev=>!onlyLy||(ev.metaType===0x05||ev.metaType===0x01));rows.forEach(ev=>{const tr=document.createElement('tr');const typeName=metaName(ev);const ms=(ev.playTime||0).toFixed(0);const rendered=interpret?renderSoftKaraoke(ev.text):highlightKeyChars(ev.text);tr.innerHTML=`<td>${ev.track}</td><td>${ev.idx}</td><td>${typeName}</td><td>${ev.delta??''}</td><td>${ms}</td><td>${rendered}</td>`;tbody.appendChild(tr);});}
function metaName(ev){if(ev.type===MIDIFile.EVENT_META){switch(ev.metaType){case 0x01:return'FF01 Text';case 0x02:return'FF02 Copyright';case 0x03:return'FF03 TrackName';case 0x04:return'FF04 Instrument';case 0x05:return'FF05 Lyric';case 0x06:return'FF06 Marker';case 0x07:return'FF07 CuePoint';case 0x2F:return'FF2F EndOfTrack';case 0x51:return'FF51 Tempo';case 0x54:return'FF54 SMPTE';case 0x58:return'FF58 TimeSig';case 0x59:return'FF59 KeySig';case 0x7F:return'FF7F Sequencer';default:return`FF${ev.metaType?.toString(16).padStart(2,'0').toUpperCase()}`;} } return'MIDI';}

function renderSoftKaraoke(txt=''){const chip=(label,cls='chip')=>`<span class="${cls}">${label}</span>`;const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));let out='';if(txt.startsWith('\')) out+=chip('CLEAR/LINE (\)')+' ';if(txt.startsWith('/')) out+=chip('PARA (/)')+' ';out+=esc(txt).replace(/\r/g,chip('CR')).replace(/\n/g,chip('LF')).replace(/\t/g,chip('TAB')).replace(/\\/g,chip('\')).replace(/\\{/g,chip('{')).replace(/\\}/g,chip('}')).replace(/\\[/g,chip('[')).replace(/\\]/g,chip(']')).replace(/\[([^\]]+)\]/g,(_,ruby)=>chip(`RUBY[${ruby}]`)).replace(/\{\@([^}]+)\}/g,(_,lang)=>chip(`LANG{${lang}}`)).replace(/\{\#([^}]+)\}/g,(_,info)=>chip(`INFO{${info}}`)).replace(/\/g,chip('\')).replace(/\//g,chip('/')).replace(/-/g,chip('-'));return out;}
function highlightKeyChars(txt=''){const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const map={'\':'<span class="chip">\</span>','/':'<span class="chip">/</span>','-':'<span class="chip">-</span>','[':'<span class="chip">[</span>',']':'<span class="chip">]</span>','{':'<span class="chip">{</span>','}':'<span class="chip">}</span>'};let out='';for(const ch of txt) out+=(map[ch]??esc(ch));return out;}

document.getElementById('btnStfLoad').addEventListener('click',()=>{if(!midiFile) return showMsg('Parse a MIDI/KAR first.');const gap=Math.max(1,parseInt(document.getElementById('stfGap').value||'15',10));const isMs=document.getElementById('stfIsMs').checked;tokens=stfToTokens(document.getElementById('stfBox').value,gap,isMs);renderTokens();showMsg(`Loaded STF -> ${tokens.length} tokens.`);});
function stfToTokens(stfText,gap,isMs){const lines=stfText.replace(//g,'').split('
');const toks=[];for(const r0 of lines){const r=r0.trim();if(!r) continue;let tick=null,text='';if(isMs){const m=r.match(/^\[(\d{1,2}):(\d{2})[.:](\d{2})\]\s*(.+)$/);if(m){const ms=(+m[1])*60000+(+m[2])*1000+(+m[3])*10;tick=msToTick(ms);text=m[4];}}else{const m=r.match(/^\[(\d+)\]\s*(.+)$/);if(m){tick=+m[1];text=m[2];}}if(tick==null) continue;let cur=tick;for(const tok of text.split(/\s+/)){if(!tok) continue;if(tok.includes('-')){for(const seg of karakanSplit(tok)){toks.push({tick:cur,text:seg});cur+=gap;}}else{toks.push({tick:cur,text:tok+' '});cur+=gap;}}}return toks;}
function karakanSplit(word){const parts=word.split(/-+/).filter(Boolean);return parts.map((seg,i)=>(i<parts.length-1)?(seg+'-'):(seg+' '));}

document.getElementById('btnAutoLoad').addEventListener('click',()=>{if(!midiFile) return showMsg('Parse a MIDI/KAR first.');const gap=Math.max(1,parseInt(document.getElementById('autoGap').value||'15',10));const ff05=midiFile.getLyrics()||[];const ff01=allEvents.filter(ev=>ev.type===MIDIFile.EVENT_META&&ev.metaType===0x01&&ev.text);const pick=ff05.length?ff05.map(l=>({tick:msToTick(l.playTime),text:l.text})):ff01.map(e=>({tick:msToTick(e.playTime||0),text:e.text}));tokens=[];for(const e of pick){let cur=e.tick;for(const w of e.text.split(/\s+/)){if(!w) continue;if(w.includes('-')){for(const seg of karakanSplit(w)){tokens.push({tick:cur,text:seg});cur+=gap;}}else{tokens.push({tick:cur,text:w+' '});cur+=gap;}}}renderTokens();showMsg(`Auto-load OK. Chosen=${ff05.length?'FF05':'FF01'}; tokens=${tokens.length}.`);});

document.getElementById('btnClearTokens').addEventListener('click',()=>{tokens=[];renderTokens();});

function renderTokens(){const tbody=document.querySelector('#tokensTbl tbody');tbody.innerHTML='';tokens.forEach(t=>{const tr=document.createElement('tr');tr.innerHTML=`<td><input type="number" name="wtick[]" value="${t.tick}" min="0"></td><td><input type="text" name="wtext[]" value="${t.text}"></td>`;tbody.appendChild(tr);});}

function buildTempoSegments(){const segs=[{ms:0,usPerQN:500000}];allEvents.forEach(ev=>{if(ev.type===MIDIFile.EVENT_META&&ev.metaType===0x51&&ev.playTime!=null){const usPerQN=ev.tempo?Math.round(ev.tempo*1000):500000;segs.push({ms:Math.round(ev.playTime),usPerQN});}});segs.sort((a,b)=>a.ms-b.ms);const out=[];for(const s of segs){if(!out.length||out[out.length-1].ms!==s.ms) out.push(s);else out[out.length-1]=s;}return out;}
function msToTick(ms){if(header.timeDivision===MIDIFile.Header.TICKS_PER_BEAT){const segs=buildTempoSegments();let prevMs=0,prevUs=segs[0].usPerQN,ticks=0;for(let i=1;i<segs.length&&segs[i].ms<=ms;i++){const dt=segs[i].ms-prevMs;ticks+=dt*1000*ticksPerBeat/prevUs;prevMs=segs[i].ms;prevUs=segs[i].usPerQN;}ticks+=(ms-prevMs)*1000*ticksPerBeat/prevUs;return Math.round(ticks);}else{const fpsByte=(header.timeDivision>>8)&0xFF,fps=256-fpsByte,tpf=header.timeDivision&0xFF;return Math.round(ms*fps*tpf/1000);}}

// Embed

document.getElementById('btnEmbed').addEventListener('click',()=>{if(!midiFile||!tokens.length) return showMsg('No tokens to embed.');const strip=document.getElementById('stripFF05').checked,forceKar=document.getElementById('forceKar').checked;try{const out=buildEmbeddedFile(tokens,strip);const base=(document.getElementById('fileInput').files[0]?.name||'output').replace(/\.[^.]+$/,'');const ext=forceKar?'kar':((/\.(mid|midi)$/i).test(document.getElementById('fileInput').files[0]?.name||'')?'mid':'kar');const blob=new Blob([out],{type:'audio/midi'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${base}_lyrics.${ext}`;a.click();showMsg(`Embedded -> ${a.download}`);}catch(e){console.error(e);showMsg('Failed to embed.');}});

function buildEmbeddedFile(karTokens,stripFF05){const bytes=new Uint8Array(arrayBuffer);const hdrLen=(bytes[4]<<24)|(bytes[5]<<16)|(bytes[6]<<8)|bytes[7],format=(bytes[8]<<8)|bytes[9],nTracks=(bytes[10]<<8)|bytes[11],divisionRaw=(bytes[12]<<8)|bytes[13];let pos=8+hdrLen;const chunks=[];for(let i=0;i<nTracks;i++){if(bytes[pos]!==0x4D||bytes[pos+1]!==0x54||bytes[pos+2]!==0x72||bytes[pos+3]!==0x6B) break;const len=(bytes[pos+4]<<24)|(bytes[pos+5]<<16)|(bytes[pos+6]<<8)|bytes[pos+7];const chunk=bytes.slice(pos,pos+8+len);chunks.push(stripFF05?stripFF05Track(chunk):chunk);pos+=8+len;}const headerOut=buildHeader(format,nTracks+1,divisionRaw),lyrTrk=buildLyricsTrack(karTokens);const totalLen=headerOut.length+chunks.reduce((s,c)=>s+c.length,0)+lyrTrk.length;const out=new Uint8Array(totalLen);let off=0;out.set(headerOut,off);off+=headerOut.length;for(const c of chunks){out.set(c,off);off+=c.length;}out.set(lyrTrk,off);return out.buffer;}
function buildHeader(format,nTracks,divisionRaw){const out=[];pushStr(out,'MThd');pushU32(out,6);pushU16(out,format);pushU16(out,nTracks);pushU16(out,divisionRaw);return new Uint8Array(out);} 
function buildLyricsTrack(karTokens){const body=[];pushVar(body,0);body.push(0xFF,0x03);pushVar(body,6);pushAscii(body,'Lyrics');let prev=0;for(const t of karTokens){const tick=Math.max(0,t.tick|0),delta=Math.max(0,tick-prev);prev=tick;const raw=toISO(t.text);pushVar(body,delta);body.push(0xFF,0x05);pushVar(body,raw.length);pushBytes(body,raw);}pushVar(body,0);body.push(0xFF,0x2F,0x00);const out=[];pushStr(out,'MTrk');pushU32(out,body.length);pushBytes(out,body);return new Uint8Array(out);} 
function stripFF05Track(chunk){const data=chunk.slice(8);let p=0,carry=0,run=0;const out=[];while(p<data.length){const [delta,dsz]=readVar(data,p);p+=dsz;const status=data[p];if(status===0xFF){p++;const type=data[p++];const [mlen,msz]=readVar(data,p);p+=msz;const payload=data.slice(p,p+mlen);p+=mlen;const newDelta=carry+delta;carry=0;if(type===0x2F){carry+=newDelta;continue;}if(type===0x05){carry=newDelta;continue;}pushVar(out,newDelta);out.push(0xFF,type);pushVar(out,payload.length);pushBytes(out,payload);}else if(status===0xF0||status===0xF7){p++;const [mlen,msz]=readVar(data,p);p+=msz;const payload=data.slice(p,p+mlen);p+=mlen;const newDelta=carry+delta;carry=0;pushVar(out,newDelta);out.push(status);pushVar(out,payload.length);pushBytes(out,payload);}else{let bytes=[];if(status<0x80){const d1=status;const st=run;const hi=st&0xF0;if(hi===0xC0||hi===0xD0){bytes=[st,d1];}else{const d2=data[p++];bytes=[st,d1,d2];}}else{run=status;const hi=status&0xF0;p++;if(hi===0xC0||hi===0xD0){const d1=data[p++];bytes=[status,d1];}else{const d1=data[p++],d2=data[p++];bytes=[status,d1,d2];}}const newDelta=carry+delta;carry=0;pushVar(out,newDelta);pushBytes(out,bytes);} } pushVar(out,carry);out.push(0xFF,0x2F,0x00);const body=new Uint8Array(out);const outChunk=new Uint8Array(8+body.length);outChunk.set(strBytes('MTrk'),0);pushU32ToArray(outChunk,4,body.length);outChunk.set(body,8);return outChunk;}
function pushStr(out,s){for(const c of s) out.push(c.charCodeAt(0));}
function pushBytes(out,bytes){for(const b of bytes) out.push(b);} 
function pushU16(out,v){out.push((v>>8)&0xFF,v&0xFF);} 
function pushU32(out,v){out.push((v>>24)&0xFF,(v>>16)&0xFF,(v>>8)&0xFF,v&0xFF);} 
function pushU32ToArray(arr,pos,v){arr[pos]=(v>>24)&0xFF;arr[pos+1]=(v>>16)&0xFF;arr[pos+2]=(v>>8)&0xFF;arr[pos+3]=v&0xFF;} 
function pushVar(out,v){const bytes=[v&0x7F];v>>=7;while(v>0){bytes.push((v&0x7F)|0x80);v>>=7;}for(let i=bytes.length-1;i>=0;i--) out.push(bytes[i]);} 
function readVar(data,p){let v=0,c=0;while(true){const b=data[p++];v=(v<<7)|(b&0x7F);c++;if(!(b&0x80)) break;}return [v,c];}
function strBytes(s){const a=[];for(const c of s) a.push(c.charCodeAt(0));return new Uint8Array(a);} 
function pushAscii(out,s){for(const c of s) out.push(c.charCodeAt(0));} 
function toISO(s){const out=[];for(const ch of s){const code=ch.charCodeAt(0);out.push(code<256?code:0x3F);}return new Uint8Array(out);} 
