
(function () {
  function bn(p) { try { return (p || '').split('/').pop(); } catch { return p || ''; } }
  function stripExt(n) { const i = n.lastIndexOf('.'); return i > 0 ? n.slice(0, i) : n; }
  function esc(s) { return (s == null ? '' : String(s)).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c])); }
  function ensurePanelAndSearch(filename) {
    if (window.WM && WM.songinfo && typeof WM.songinfo.show === 'function') { WM.songinfo.show(); }
    else { const p = document.getElementById('songInfoPanel'); if (p) { p.classList.add('visible'); p.style.zIndex = '400'; } }
    const q = document.getElementById('songInfoQuery'); if (q) q.value = stripExt(bn(filename || ''));
    const go = document.getElementById('songInfoGo'); if (go) { try { go.click(); } catch { } }
  }
  function addIconToRow(row) {
    if (!row || row.querySelector('.songinfo-mini')) return; const link = row.querySelector('a.song'); if (!link) return;
    const mini = document.createElement('a'); mini.href = '#'; mini.className = 'btn small songinfo-mini'; mini.title = 'Song Info (Online)'; mini.textContent = 'ⓘ'; mini.style.marginLeft = '6px';
    mini.addEventListener('click', function (e) { e.preventDefault(); const filename = link.textContent || link.innerText || ''; ensurePanelAndSearch(filename); });
    const size = row.querySelector('.small'); if (size && size.parentNode) size.parentNode.insertBefore(mini, size.nextSibling); else row.appendChild(mini);
  }
  function decoratePlaylist() { const list = document.getElementById('playlist'); if (!list) return false; list.querySelectorAll('.row').forEach(addIconToRow); return true; }
  function watchPlaylist() { const list = document.getElementById('playlist'); if (!list) return; const mo = new MutationObserver(muts => { for (const m of muts) { if (m.addedNodes && m.addedNodes.length) decoratePlaylist(); } }); mo.observe(list, { childList: true, subtree: true }); }
  function hookPlaylist() { let tries = 0, max = 15; (function tick() { tries++; const ok = decoratePlaylist(); if (ok) { watchPlaylist(); return; } if (tries < max) setTimeout(tick, 400); })(); }
  function fetchTO(url, ms) { const ctrl = new AbortController(); const t = setTimeout(() => { try { ctrl.abort(); } catch { } }, ms || 10000); return fetch(url, { signal: ctrl.signal }).finally(() => clearTimeout(t)); }
  function qMBRecording(title, artist) { const q = (title && artist) ? `recording:"${title}" AND artist:"${artist}"` : `"${String((title || artist || '')).trim()}"`; const url = `https://musicbrainz.org/ws/2/recording?query=${encodeURIComponent(q)}&fmt=json&limit=5`; return fetchTO(url, 10000).then(r => (r && r.ok ? r.json() : null)); }
  function mbRecordingReleases(id) { const url = `https://musicbrainz.org/ws/2/recording/${encodeURIComponent(id)}?inc=releases&fmt=json`; return fetch(url, { headers: { 'User-Agent': 'KHD SongInfo/1.0 (non-commercial)' } }).then(r => (r && r.ok ? r.json() : null)); }
  function qCAA(relMBID) { const url = `https://coverartarchive.org/release/${encodeURIComponent(relMBID)}/`; return fetch(url, { headers: { 'Accept': 'application/json' } }).then(r => (r && r.ok ? r.json() : null)).then(d => { if (!d || !Array.isArray(d.images) || !d.images.length) return null; const pick = d.images.find(x => x.front) || d.images[0]; const tn = pick.thumbnails || {}; return { small: tn['250'] || tn.small || pick.image, large: tn['500'] || tn.large || pick.image, full: pick.image || '', types: pick.types || [], relUrl: d.release || '' }; }); }
  function guessFromInput() { const q = document.getElementById('songInfoQuery'); let txt = q && q.value ? q.value : ''; if (!txt) { try { const nm = (window.lastPlayed && lastPlayed.name) ? lastPlayed.name : (window.currentSong || ''); txt = stripExt(bn(nm || '')); } catch { } } return txt; }
  function parseAT(s) { const raw = String(s || '').trim(); let artist = '', title = ''; if (raw.indexOf(' - ') >= 0) { const A = raw.split(' - '); const left = A[0].trim(); const right = A.slice(1).join(' - ').trim(); const rightArtist = /\b(feat\.?|ft\.? )\b/i.test(right) || /^[A-Z][a-z]+(\s+[A-Z][a-z]+)+$/.test(right); if (rightArtist) { title = left; artist = right.replace(/\b(feat\.?|ft\.? )\b.*$/i, '').trim(); } else { artist = left.replace(/\b(feat\.?|ft\.? )\b.*$/i, '').trim(); title = right; } } else { title = raw; } return { title, artist }; }
  function appendCAA() { const res = document.getElementById('songInfoResults'); if (!res) return; const s = guessFromInput(); const g = parseAT(s); if (!g.title && !g.artist) return; qMBRecording(g.title, g.artist).then(MB => { if (!MB || !Array.isArray(MB.recordings) || !MB.recordings.length) return; const rec = MB.recordings[0]; return mbRecordingReleases(rec.id).then(det => { const rels = det && det.releases || []; if (!rels.length) return; const relMBID = rels[0].id || ''; const relTitle = rels[0].title || g.title; return qCAA(relMBID).then(caa => { if (!caa) return; const wrap = document.createElement('div'); wrap.className = 'row'; wrap.innerHTML = (caa.small ? (`<img src="${esc(caa.small)}" alt="" style="width:48px;height:48px;border-radius:6px;object-fit:cover">`) : '') + `<div style="flex:1"><div style="font-weight:700">${esc(relTitle)} — Cover Art</div><div class="small">${(caa.types && caa.types.length ? esc(caa.types.join(', ')) + ' • ' : '')}Cover Art Archive</div><div style="display:flex;gap:6px;flex-wrap:wrap">${caa.large ? `<a class="btn small" href="${esc(caa.large)}" target="_blank" rel="noopener">View 500px</a>` : ''}${caa.full ? `<a class="btn small" href="${esc(caa.full)}" target="_blank" rel="noopener">Full image</a>` : ''}${caa.relUrl ? `<a class="btn small" href="${esc(caa.relUrl)}" target="_blank" rel="noopener">MB Release</a>` : ''}</div></div>`; res.appendChild(wrap); }); }); }).catch(() => { }); }
  function watchResults() { const res = document.getElementById('songInfoResults'); if (!res) return; const mo = new MutationObserver(() => { try { mo.disconnect(); } catch { } setTimeout(appendCAA, 120); }); mo.observe(res, { childList: true, subtree: false }); }
  function hookEnhance() { let tries = 0, max = 15; (function tick() { tries++; if (document.getElementById('songInfoResults')) { watchResults(); return; } if (tries < max) setTimeout(tick, 400); })(); }
  if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', () => { hookPlaylist(); hookEnhance(); }); } else { hookPlaylist(); hookEnhance(); }
  window.__SONGINFO_ADDONS = { rehook: () => { hookPlaylist(); hookEnhance(); } };
})();
